##########################################################################
################################# TOKENS #################################
##########################################################################

@user_token = 

##########################################################################
################################## API ##################################
##########################################################################

@index = http://127.0.0.1:8000/
@calculate_body = http://127.0.0.1:8000/calculate_body/
@calculate_path = http://127.0.0.1:8000/calculate_path/
@users = http://127.0.0.1:8000/users/

###
GET {{index}} HTTP/1.1

###
POST {{calculate_path}}?num1=1&num2=2 HTTP/1.1

###
POST {{calculate_body}} HTTP/1.1
Content-Type: application/json

{
    "num1": 5,
    "num2": 10
}

###
GET {{users}} HTTP/1.1

###
GET {{users}}?offset=2&limit=5 HTTP/1.1

###
GET {{users}}1/ HTTP/1.1

###
POST {{users}} HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "name": "Ivan",
    "age": 18
}
