version: '3.8'

volumes:
  tradings_fastapi_database_volume:

services:

  tradings_fastapi_database:
    image: postgres:12-alpine
    volumes:
      - tradings_fastapi_database_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  tradings_fastapi_pg_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - tradings_fastapi_database
